import { Atc } from "./fhirUtils/Atc";
import { Attachment } from "./fhirUtils/Attachment";
import { AuditEvent } from "./fhirUtils/AuditEvent";
import { Bundle } from "./fhirUtils/Bundle";
import { BundleMessage } from "./fhirUtils/BundleMessage";
import { CodeableConcept } from "./fhirUtils/CodeableConcept";
import { CommonFHIR } from "./fhirUtils/CommonFHIR";
import { Communication } from "./fhirUtils/Communication";
import { Composition } from "./fhirUtils/Composition";
import { Covid19 } from "./fhirUtils/Covid19";
import { DiagnosticReport } from "./fhirUtils/DiagnosticReport";
import { DocumentReference } from "./fhirUtils/DocumentReference";
import { Hl7 } from "./fhirUtils/Hl7";
import { Identifier } from "./fhirUtils/Identifier";
import { ImagingStudy } from "./fhirUtils/ImagingStudy";
import { Immunization } from "./fhirUtils/Immunization";
import { Loinc } from "./fhirUtils/Loinc";
import { Personal } from "./fhirUtils/Personal";
import { Quantity } from "./fhirUtils/Quantity";
import { Reference } from "./fhirUtils/Reference";
import { Sections } from "./fhirUtils/Sections";
import { Snomed } from "./fhirUtils/Snomed";
export declare class FhirUtils {
    atc: Atc;
    attachment: Attachment;
    auditEvent: AuditEvent;
    bundle: Bundle;
    bundleMessage: BundleMessage;
    codeableConcept: CodeableConcept;
    commonFHIR: CommonFHIR;
    communication: Communication;
    composition: Composition;
    covid19: Covid19;
    diagnosticReport: DiagnosticReport;
    documentReference: DocumentReference;
    hl7: Hl7;
    identifier: Identifier;
    imagingStudy: ImagingStudy;
    immunization: Immunization;
    loinc: Loinc;
    personal: Personal;
    quantity: Quantity;
    reference: Reference;
    sections: Sections;
    snomed: Snomed;
    constructor();
}
