import { Attachment } from "./fhirUtils/Attachment";
import { Bundle } from "./fhirUtils/Bundle";
import { BundleMessage } from "./fhirUtils/BundleMessage";
import { CodeableConcept } from "./fhirUtils/CodeableConcept";
import { Composition } from "./fhirUtils/Composition";
import { CommonFHIR } from "./fhirUtils/CommonFHIR";
import { DiagnosticReport } from "./fhirUtils/DiagnosticReport";
import { DocumentReference } from "./fhirUtils/DocumentReference";
import { Identifier } from "./fhirUtils/Identifier";
import { ImagingStudy } from "./fhirUtils/ImagingStudy";
import { Immunization } from "./fhirUtils/Immunization";
import { Hl7 } from "./fhirUtils/Hl7";
import { Loinc } from "./fhirUtils/Loinc";
import { Snomed } from "./fhirUtils/Snomed";
import { Reference } from "./fhirUtils/Reference";
import { Quantity } from "./fhirUtils/Quantity";
export declare class FhirUtils {
    attachment: Attachment;
    bundle: Bundle;
    bundleMessage: BundleMessage;
    codeableConcept: CodeableConcept;
    commonFHIR: CommonFHIR;
    composition: Composition;
    diagnosticReport: DiagnosticReport;
    documentReference: DocumentReference;
    identifier: Identifier;
    imagingStudy: ImagingStudy;
    immunization: Immunization;
    hl7: Hl7;
    loinc: Loinc;
    snomed: Snomed;
    references: Reference;
    quantity: Quantity;
    constructor();
}
