import { R4 } from "@ahryman40k/ts-fhir-types";
export declare function getTimestamp(fhirBundle: R4.IBundle): string;
export declare function addResourceToBundle(bundle: R4.IBundle, resource: any, sectionCode?: string, sectionSystem?: string): R4.IBundle;
export declare function addAdditionalResourcesToBundle(bundle: R4.IBundle, resources?: any[], sectionCode?: string, sectionSystem?: string): R4.IBundle;
export declare function createBundleDocumentWithComposition(resources?: any[], authorReferenceId?: string, typeDocumentCodeLOINC?: string): R4.IBundle;
export declare function isIPS(bundleDocument: R4.IBundle): boolean;
export declare function createEmptyIPS(authorReferenceId: string): R4.IBundle;
export declare function addEntriesToBundle(bundle: R4.IBundle, entries: R4.IBundle_Entry[]): R4.IBundle;
export declare function addResourcesBySection(bundleDocument: R4.IBundle, sectionCode: string, sectionSystem: string, resources: any[]): R4.IBundle;
export declare function addEntriesBySection(bundleDocument: R4.IBundle, bundleEntries: R4.IBundle_Entry[], sectionCode: string, sectionSystem: string): R4.IBundle;
export declare function getReferencesInSection(section: R4.IComposition_Section): R4.IReference[];
export declare function getResourcesInSection(bundleDocument: R4.IBundle, sectionCode: string, sectionSystem?: string): any[];
export declare function getAllResourcesInBundleEntries(bundle: R4.IBundle): any[];
export declare function getAllResourcesWithoutCompositionOrMessageHeader(bundle: R4.IBundle): any[];
export declare function getResourceIdsInBundle(bundle: R4.IBundle): string[];
export declare function getResourcesByTypes(bundle: R4.IBundle, resourceTypes: string[]): any[];
export declare function getResourceByIdInBundle(resourceId: string, bundle: R4.IBundle): any;
export declare function getObservationsByCode(bundle: R4.IBundle, code: string): any[];
export declare function replaceResourceById(resource: any, bundle: R4.IBundle): R4.IBundle;
export declare function getMediaInBundle(bundle: R4.IBundle): R4.IMedia[];
